apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-actor

bases:
- ../../base

replicas:
- name: spring-actor
  count: 3

patchesStrategicMerge:
- service-patch.yaml
- deployment-patch.yaml
