apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-actor

resources:
- namespace.yaml
- rbac.yaml
- configmap.yaml
- service.yaml
- deployment.yaml
- servicemonitor.yaml
- podmonitor.yaml
- networkpolicy.yaml

commonLabels:
  app: spring-actor
  managed-by: kustomize

images:
- name: your-registry/spring-actor-app
  newTag: latest
