apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-actor
  namespace: spring-actor
  labels:
    app: spring-actor
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: spring-actor
  podMetricsEndpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
  - port: management
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - spring-actor
