---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-actor-sa
  labels:
    app: spring-actor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-actor-pod-reader
  labels:
    app: spring-actor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-actor-pod-reader-binding
  labels:
    app: spring-actor
subjects:
- kind: ServiceAccount
  name: spring-actor-sa
roleRef:
  kind: Role
  name: spring-actor-pod-reader
  apiGroup: rbac.authorization.k8s.io
